# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.FileField(default=0, upload_to=''),
        ),
    ]
