# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20170821_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(default='/inst-icon.png', upload_to=''),
        ),
    ]
