# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('rating',)},
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
