# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20170825_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('-rating',)},
        ),
    ]
