# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20170825_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(default='/no_image.png', upload_to='profiles'),
        ),
    ]
